version: "3.8"
services:
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3.7.7-management-alpine
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "127.0.0.1:5673:5672"
            - "127.0.0.1:15673:15672"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
